# Generated by Django 2.2 on 2019-08-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
