# Generated by Django 2.2 on 2019-08-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20190805_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
